codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  range: "70...100"
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

ignore:
  - "tests/"
  - "**/__pycache__"
